---
config:
    theme: neutral
---

flowchart TD

    %% base structure
    root["NextToken()"] --> sws("SkipWhiteSpace()") --> case{case}

    %% Characters
    bo(("{"))
    eo(("}"))
    ba(("[")) 
    ea(("]"))
    ns((":"))
    vs((","))

    %% Return values
    subgraph Rt1["Token"]
        t1["type: BeginObject"]
        l1["literal: {"]
    end

    subgraph Rt2["Token"]
        t2["type: EndObject"]
        l2["literal: }"]
    end

    subgraph Rt3["Token"]
        t3["type: BeginArray"]
        l3["literal: ["]
    end

    subgraph Rt4["Token"]
        t4["type: EndArray"]
        l4["literal: ]"]
    end

    subgraph Rt5["Token"]
        t5["type: NameSeparator"]
        l5["literal: :"]
    end

    subgraph Rt6["Token"]
        t6["type: ValueSeparator"]
        l6["literal: ,"]
    end

    %% Flow
    case --> bo --> Rt1
    case --> eo --> Rt2
    case --> ba --> Rt3
    case --> ea --> Rt4
    case --> ns --> Rt5
    case --> vs --> Rt6