flowchart TD

    %% base structure
    root["NextToken()"] --> sws["SkipWhiteSpace()"] --> case{case}

    %% Characters
    bo["{"]
    eo["}"]
    ba["["]
    ea["]"]
    ns[":"]
    vs[","]
    str["string"]
    eof["EOF (0)"]
    df["default"]
    dgom["digit or -"]
    lit["literal"]

    %% Functions
    rn["ReadNum()"]
    rl["ReadLiteral()"]
    rs["ReadString()"]

    %% Return values
    t_bo["BeginObject Token"]
    t_eo["EndObject Token"]
    t_ba["BeginArray Token"]
    t_ea["EndArray Token"]
    t_ns["NameSeparator Token"]
    t_vs["ValueSeparator Token"]
    t_str["String Token"]
    t_num["Number Token"]
    t_lit["True/False/Null Token"]
    t_eof["EOF"]
    t_illegal["Illegal Token"]

    %% Flow
    case --> bo --> t_bo
    case --> eo --> t_eo
    case --> ba --> t_ba
    case --> ea --> t_ea
    case --> str --> rs --> t_str
    case --> ns --> t_ns
    case --> vs --> t_vs
    case --> eof --> t_eof

    case --> df --> cond{if}

    cond --> dgom --> rn --> t_num
    cond --> lit --> rl --> t_lit
    cond -->|"else"| t_illegal